### ISSUE TITLE
buildTasks are skipped

### ISSUE THREAD

**Issue by zhen-lu** [F43nd1r/gradle-release#1] opened 2020-08-20 18:01 UTC
The related build.gradle codes:
```groovy
release {
    buildTasks = ['build']
    failOnCommitNeeded = true
    failOnPublishNeeded = true
    failOnSnapshotDependencies = true
    failOnUnversionedFiles = true
    failOnUpdateNeeded = true
    pushReleaseVersionBranch = "release"
    revertOnFail = true
    git {
        pushToRemote = "origin"
        requireBranch = "release"
    }
    tagTemplate = 'v$version'
}

runBuildTasks {
    afterEvaluate {
        println 'Hello afterEvaluate!'
    }

    doLast {
        println 'Hello println!'
    }

    beforeReleaseBuild.finalizedBy publish
}
```

The output from manually trigger the task runBuildTasks:
```3:45:42 am: Executing task 'runBuildTasks'...

Configuration on demand is an incubating feature.

> Configure project :
Hello afterEvaluate!

> Configure project :shaper-core
Hello afterEvaluate!

> Task :shaper-core:data:publish UP-TO-DATE
> Task :shaper-core:collections-sal:publish UP-TO-DATE
> Task :shaper-core:feature-switch:publish UP-TO-DATE
> Task :shaper-core:collections-model:publish UP-TO-DATE
> Task :shaper-core:server:publish UP-TO-DATE
> Task :shaper-core:beforeReleaseBuild
> Task :shaper-core:publish UP-TO-DATE
> Task :shaper-core:compileJava NO-SOURCE
> Task :shaper-core:processResources NO-SOURCE
> Task :shaper-core:classes UP-TO-DATE
> Task :shaper-core:jar UP-TO-DATE
> Task :shaper-core:assemble UP-TO-DATE
> Task :shaper-core:spotbugsMain NO-SOURCE
> Task :shaper-core:compileTestJava NO-SOURCE
> Task :shaper-core:processTestResources NO-SOURCE
> Task :shaper-core:testClasses UP-TO-DATE
> Task :shaper-core:spotbugsTest NO-SOURCE
> Task :shaper-core:test NO-SOURCE
> Task :shaper-core:check UP-TO-DATE
> Task :shaper-core:build UP-TO-DATE
> Task :shaper-core:afterReleaseBuild

> Task :runBuildTasks
Hello println!

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
```

**Comment by F43nd1r** [comment] 2020-08-20 18:09
Alright, and what's the issue? All your debug statements show up, and both `:build` and `:runBuildTasks` are called.

**Comment by zhen-lu** [comment] 2020-08-20 18:17
> Alright, and what's the issue? All your debug statements show up, and both `:build` and `:runBuildTasks` are called.

The problem is that those are all marked as 'UP-TO-DATE' and no actual action at all ...

**Comment by F43nd1r** [comment] 2020-08-20 18:24
And what's the output of `gradle clean runBuildTasks`?

**Comment by zhen-lu** [comment] 2020-08-20 18:28
> And what's the output of `gradle clean runBuildTasks`?

% ./gradlew clean --rerun-tasks runBuildTasks
Configuration on demand is an incubating feature.

> Configure project :
Hello afterEvaluate!

> Configure project :shaper-core
Hello afterEvaluate!

> Task :shaper-core:build
build complete

> Task :runBuildTasks
Hello println!

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 791ms
7 actionable tasks: 7 executed

The problem here is the build task is not actually executed still...

**Comment by zhen-lu** [comment] 2020-08-20 18:31
Tried the trick mentioned here: https://stackoverflow.com/questions/42175235/force-gradle-to-run-task-even-if-it-is-up-to-date by adding:

`
build {
    outputs.upToDateWhen { false }
    doLast {
        println "build complete"
    }
}
`

Still no luck

**Comment by F43nd1r** [comment] 2020-08-20 18:40
>     Task :shaper-core:build
>     build complete


Gradle certainly thinks `build` was executed. The problem seems to be deeper in your project. Is it open source so I can play around with it myself?

**Comment by zhen-lu** [comment] 2020-08-20 18:43
> > ```
> > Task :shaper-core:build
> > build complete
> > ```
> 
> Gradle certainly thinks `build` was executed. The problem seems to be deeper in your project. Is it open source so I can play around with it myself?

it's a company repo; maybe I could extract the minimal pieces together as a sample project to demo this; might take sometime though

**Comment by F43nd1r** [comment] 2020-08-20 18:45
Sounds good. I don't think I can debug this without seeing it myself.

**Comment by ZhenLu101** [comment] 2020-08-20 21:46
> Sounds good. I don't think I can debug this without seeing it myself.

put together a small repo here: https://github.com/ZhenLu101/shaper-core

This works:
`
./gradlew build
`

but this does not actually build:
`
% ./gradlew clean --rerun-tasks runBuildTasks
Configuration on demand is an incubating feature.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 738ms
5 actionable tasks: 2 executed, 3 up-to-date
`


The build task is marked as `
> Task :shaper-core:build UP-TO-DATE
`
and no action there at all

**Comment by F43nd1r** [comment] 2020-08-20 22:33
Seems like the root cause is this: `build` is only run in the parent project, not subprojects. Here's a quick fix:
```groovy
release {
    subprojects {
        buildTasks += "$project.name:build"
    }
}
```

However, this should not be the case. I'll investigate further why this happens.

**Comment by F43nd1r** [comment] 2020-08-20 23:57
Fixed in eb48efe

**Closed as completed by F43nd1r** 2020-08-20 23:57 UTC

**Comment by ZhenLu101** [comment] 2020-08-21 00:25
> Fixed in [eb48efe](https://github.com/F43nd1r/gradle-release/commit/eb48efe803305202b8d7371e9edc64be65860ebc)

wow that's great!!! Thanks alot 👍

**Comment by zhen-lu** [comment] 2020-08-21 20:02
> Fixed in [eb48efe](https://github.com/F43nd1r/gradle-release/commit/eb48efe803305202b8d7371e9edc64be65860ebc)

Is there any estimate the ETA of the next release with this change? Thanks

**Comment by F43nd1r** [comment] 2020-08-23 17:28
Released just now.

**Comment by zhen-lu** [comment] 2020-08-25 18:45
awesome v3.3.1 triggered publish job which does published artefacts as expected 👍

**Comment by zhen-lu** [comment] 2020-08-25 20:25
used version 3.3.1 on buildkite pipeline somehow still met the issue that publish task takes no action; had to add this to make it work:

`
subprojects {
    buildTasks += "$project.name:build"
    buildTasks += "$project.name:publish"
}
`
